#!/bin/zsh

cp -r ~/.oh-my-zsh ~/dotfiles/.
cp -r ~/.themes ~/dotfiles/.
cp -r ~/.p10k.zsh ~/dotfiles/.
cp -r ~/.config/kitty ~/dotfiles/.
cp -r ~/.config/nvim ~/dotfiles/.

cd ~/dotfiles/

git pull

git add .
git commit -m "automatico portatil"
git push
