#!/bin/zsh

mv -r ~/.oh-my-zsh ~/dotfiles/.
mv -r ~/.themes ~/dotfiles/.
mv -r ~/.p10k.zsh ~/dotfiles/.
mv -r ~/.config/kitty ~/dotfiles/.
mv -r ~/.config/nvim ~/dotfiles/.

cd ~/dotfiles/

git pull

git add .
git commit -m "automatico portatil"
git push
