#!/bin/zsh

mv ~/.oh-my-zsh ~/dotfiles/.
mv ~/.themes ~/dotfiles/.
mv ~/.p10k.zsh ~/dotfiles/.
mv ~/.config/kitty ~/dotfiles/.
mv ~/.config/nvim ~/dotfiles/.

cd ~/dotfiles/

git pull

git add .
git commit -m "automatico portatil"
git push
